#!/usr/bin/python3

from sys import argv
from os import system

print (argv)

if argv[1] == 'serve':
    commit = False
    print ("No commit")
else:
    commit = argv[1]
system('./SimplePreprocessor/spp -s "_posts"')
if commit:
    system('jekyll build')
    system('git add .')
    system('git add -u')
    system('git commit -m ' + commit)
    system('git push origin master')
    system('git add .')
    system('git add -u')
    print ('git commit -m "' + commit.replace("\"", "") + ' (Saving actual state of my computer so git diff works; cannot push because that breaks the website.)"')
    system('git commit -m "' + commit.replace("\"", "") + ' (Saving actual state of my computer so git diff works; cannot push because that breaks the website.)"')
else:
    system('jekyll serve')
system('./SimplePreprocessor/spp -s "_posts" -c')
